name: Deploy to cPanel

on:
  push:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # ২রা জুনের ওয়ার্নিং বন্ধ হবে

jobs:
  deploy:
    name: 🚀 Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: 📥 Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🏗️ Build Assets (Vite)
        run: |
          npm install
          npm run build

      - name: 📂 Sync Files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          exclude: |
            **/.git*
            **/node_modules/**
            **/tests/**
            .env
            phpunit.xml
            phpstan.neon
            .github/**
